In [100]:
from datetime import timedelta,datetime
import glob
import os
import pandas as pd
import numpy as np


data = pd.read_csv("./order_brush_order.csv", encoding="utf-8")
arr = np.array(data)
shop_s = list(set(arr[:,1]))
result = []
data['event_time'] = pd.to_datetime(data['event_time'])  
data = data.sort_values(['shopid','event_time'])
data = data.reset_index(drop=True)

cf_ans = pd.read_csv("./gg2.csv", encoding="utf-8")
arr_ans = np.array(cf_ans)
ans_shop = arr_ans[arr_ans[:,1]!='0',0]

In [33]:
# cf_ans
def check_ans(df,shopid):
    return df.loc[cf_ans['shopid'] == shopid]

In [102]:
check_ans(cf_ans,ans_shop[0])

   shopid     userid
0   10159  214988798

In [155]:
result = []
gb_df = data.groupby('shopid')
# for shop in shop_s:
shop_s = ans_shop
shop = shop_s[0]
print(shop)
# for shop in shop_s[:1]:
tmp = gb_df.get_group(shop)
# freq of userid
freq = tmp['userid'].value_counts()
# # if most user >=3
# if freq.values[0] <3:
#     break
users = [int(user) for user in freq.keys() if freq[user]>=3 ]
print(users)
tmp_time = tmp[tmp['userid'].isin(users)]['event_time']
print(list(tmp_time))
for st in tmp_time:
    et = st + timedelta(hours=1)
    tmp_new = tmp[tmp['event_time'].between(st,et)]
    freq = tmp_new['userid'].value_counts()
    print(st,'~',et)
#     print('====')
#     cr  = len(tmp_new)/len(freq)
    print(cr)
#     print('====')
print()
for et in tmp_time:
    st = et + timedelta(hours=-1)
    tmp_new = tmp[tmp['event_time'].between(st,et)]
    freq = tmp_new['userid'].value_counts()
    print(st,'~',et)
#     print('====')
#     cr  = len(tmp_new)/len(freq)
    print(cr)
#     print('====')
# def check_period(df,users):
#     check_time = np.array(df[df['userid'].isin(users)]['event_time'])
#     return check_time
# check_time = check_period(tmp,users)
# print(users,check_time)
# # tmp
# for st in check_time:
# #     st = datetime.strptime(st, "%Y-%m-%d %H:%M:%S")
#     et = st + timedelta(hours=1)
#     print(st,'~',et)

10159
[214988798, 62775725]
[Timestamp('2019-12-28 19:49:10'), Timestamp('2019-12-29 20:38:09'), Timestamp('2019-12-29 20:40:54'), Timestamp('2019-12-29 20:56:43'), Timestamp('2019-12-30 20:16:40'), Timestamp('2019-12-30 20:18:54')]
2019-12-28 19:49:10 ~ 2019-12-28 20:49:10
1.25
2019-12-29 20:38:09 ~ 2019-12-29 21:38:09
1.25
2019-12-29 20:40:54 ~ 2019-12-29 21:40:54
1.25
2019-12-29 20:56:43 ~ 2019-12-29 21:56:43
1.25
2019-12-30 20:16:40 ~ 2019-12-30 21:16:40
1.25
2019-12-30 20:18:54 ~ 2019-12-30 21:18:54
1.25

2019-12-28 18:49:10 ~ 2019-12-28 19:49:10
1.25
2019-12-29 19:38:09 ~ 2019-12-29 20:38:09
1.25
2019-12-29 19:40:54 ~ 2019-12-29 20:40:54
1.25
2019-12-29 19:56:43 ~ 2019-12-29 20:56:43
1.25
2019-12-30 19:16:40 ~ 2019-12-30 20:16:40
1.25
2019-12-30 19:18:54 ~ 2019-12-30 20:18:54
1.25

In [158]:
tmp[tmp['event_time']>='2019-12-29 19:38:09']

            orderid  shopid     userid          event_time
393  31321034505684   10159    1138092 2019-12-29 20:17:14
394  31322289392454   10159  214988798 2019-12-29 20:38:09
395  31322453873412   10159  214988798 2019-12-29 20:40:54
396  31323403482068   10159  214988798 2019-12-29 20:56:43
397  31325771154391   10159   86597297 2019-12-29 21:36:11
398  31326799620619   10159   33460585 2019-12-29 21:53:19
399  31331346069856   10159  136820136 2019-12-29 23:09:06
400  31340761430563   10159   39602449 2019-12-30 01:46:01
401  31352957630240   10159  197347891 2019-12-30 05:09:17
402  31370242085362   10159   88740722 2019-12-30 09:57:22
403  31375098601389   10159  188238946 2019-12-30 11:18:18
404  31376378541228   10159  135015978 2019-12-30 11:39:38
405  31378485733676   10159  104081601 2019-12-30 12:14:45
406  31379967851321   10159  158204473 2019-12-30 12:39:28
407  31381173237588   10159  157091574 2019-12-30 12:59:34
408  31385072662538   10159   84719294 2019-12-30 14:04:33
409  31387305513347   10159      18604 2019-12-30 14:41:45
410  31394968169009   10159  172113694 2019-12-30 16:49:28
411  31401609198130   10159    1199044 2019-12-30 18:40:10
412  31403565628683   10159  101550864 2019-12-30 19:12:46
413  31404626928211   10159   63738063 2019-12-30 19:30:26
414  31406186317456   10159  116138866 2019-12-30 19:56:27
415  31406418260440   10159   62196380 2019-12-30 20:00:18
416  31407400544636   10159   62775725 2019-12-30 20:16:40
417  31407534932790   10159   62775725 2019-12-30 20:18:54
418  31418068139892   10159  101114264 2019-12-30 23:14:29
419  31418412160473   10159  101114264 2019-12-30 23:20:12
420  31418543173504   10159   47426114 2019-12-30 23:22:23
421  31419417107434   10159  215298229 2019-12-30 23:36:57
422  31421288356200   10159  136364647 2019-12-31 00:08:08
423  31421944686154   10159  181374539 2019-12-31 00:19:05
424  31422832622108   10159   14909514 2019-12-31 00:33:52
425  31425048460235   10159   24869430 2019-12-31 01:10:48
426  31426211510179   10159   60670053 2019-12-31 01:30:11
427  31431315118584   10159   93918352 2019-12-31 02:55:15
428  31435985767624   10159   90833571 2019-12-31 04:13:05
429  31453080194394   10159  177485436 2019-12-31 08:58:00
430  31453111678001   10159    3852415 2019-12-31 08:58:31
431  31456855107731   10159  212728148 2019-12-31 10:00:55
432  31458346123017   10159     802231 2019-12-31 10:25:47
433  31462621195960   10159  127928185 2019-12-31 11:37:02
434  31466412166208   10159   58816753 2019-12-31 12:40:12
435  31476150230065   10159  210721915 2019-12-31 15:22:30
436  31477768357376   10159   20171725 2019-12-31 15:49:28
437  31479706569221   10159    1154040 2019-12-31 16:21:46
438  31482973996570   10159   71866262 2019-12-31 17:16:13
439  31487333408188   10159    3127067 2019-12-31 18:28:53
440  31487599845864   10159  168807654 2019-12-31 18:33:20
441  31488742373628   10159   94302565 2019-12-31 18:52:22
442  31495315281725   10159  157017675 2019-12-31 20:41:55
443  31501293084626   10159   87713808 2019-12-31 22:21:33
444  31502949095291   10159   98171524 2019-12-31 22:49:09

In [ ]:


data = pd.read_csv("./order_brush_order.csv", encoding="utf-8")
arr = np.array(data)
shop_s = list(set(arr[:,1]))
result = []
for shop in shop_s:
    d_shop = arr[arr[:,1]==shop,:]
    users = set(d_shop[:,2])
    b_user = "0"
    for user in users:
        order_time = d_shop[d_shop[:,2]==user,3]
        order_time = sorted(order_time)

        if len(order_time)>=3:
            if count_in_hour_v2(order_time):
                if b_user =="0":
                    b_user = [(int(user),len(order_time))]
                else:
                    b_user+= [(int(user),len(order_time))]
    if b_user == "0":
        result.append([shop,b_user])
    else:
        if len(b_user) >1:
            b_user  = sorted(b_user,key= lambda x:(-x[1],x[0]))
            if b_user[0][1]==b_user[1][1]:
                result.append([shop,str(b_user[0][0])+"&"+str(b_user[1][0])])
            else:
                result.append([shop,str(b_user[0][0])])
        else:
            result.append([shop,str(b_user[0][0])])

# df_result = pd.DataFrame(result,columns=['shopid','userid'])
# df_result.to_csv("tmp01.csv",index=False)

In [ ]:
from datetime import timedelta,datetime
import glob
import os
import pandas as pd
import numpy as np